nut.voice.Register("combine", "Copy", "Copy.", "npc/combine_soldier/vo/copy.wav")
nut.voice.Register("combine", "11-99", "11-99, Officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
nut.voice.Register("combine", "404", "404 Zone.", "npc/metropolice/vo/404zone.wav")
nut.voice.Register("combine", "Acquiring on visual", "Acquiring on visual!", "npc/metropolice/vo/acquiringonvisual.wav")
nut.voice.Register("combine", "Administer", "Administer.", "npc/metropolice/vo/administer.wav")
nut.voice.Register("combine", "Affirmative", "Affirmative.", {"npc/metropolice/vo/affirmative.wav", "npc/metropolice/vo/affirmative2.wav", "npc/combine_soldier/vo/affirmative.wav", "npc/combine_soldier/vo/affirmative2.wav"})
nut.voice.Register("combine", "You can go", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav")
nut.voice.Register("combine", "Close on suspect", "All units, close on suspect.", "npc/metropolice/vo/allunitscloseonsuspect.wav")
nut.voice.Register("combine", "Code 2", "All units, code two.", "npc/metropolice/vo/allunitscode2.wav")
nut.voice.Register("combine", "Maintain this CP", "All units, maintain this CP.", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
nut.voice.Register("combine", "All units move in", "All units, move in.", "npc/metropolice/vo/allunitsmovein.wav")
nut.voice.Register("combine", "Report location suspect", "All units, report location suspect.", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
nut.voice.Register("combine", "Amputate", "Amputate.", "npc/metropolice/vo/amputate.wav")
nut.voice.Register("combine", "Anticitizen", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav")
nut.voice.Register("combine", "Anyone pickup 647e", "Anyone pick up 647E reading?", "npc/metropolice/vo/anyonepickup647e.wav")
nut.voice.Register("combine", "Apply", "Apply.", "npc/metropolice/vo/apply.wav")
nut.voice.Register("combine", "At checkpoint", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav")
nut.voice.Register("combine", "Back me up", "Back me up. I'm out.", "npc/metropolice/vo/backmeupimout.wav")
nut.voice.Register("combine", "Back up", "Back up.", "npc/metropolice/vo/backup.wav")
nut.voice.Register("combine", "Block", "Block.", "npc/metropolice/vo/block.wav")
nut.voice.Register("combine", "Break cover", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav")
nut.voice.Register("combine", "Cauterize", "Cauterize.", "npc/metropolice/vo/cauterize.wav")
nut.voice.Register("combine", "Check for miscount", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav")
nut.voice.Register("combine", "Ha ha", "Haha.", "npc/metropolice/vo/chuckle.wav")
nut.voice.Register("combine", "Citizen", "Citizen.", "npc/metropolice/vo/citizen.wav")
nut.voice.Register("combine", "Citizen summoned", "Reporting citizen summoned into vault constriction for channel open service detail T94-32.", "npc/metropolice/vo/citizensummoned.wav")
nut.voice.Register("combine", "Confirmed sighted", "Confirmed priority one sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav")
nut.voice.Register("combine", "Control 100", "Control is one hundred percent at location, no sign of that 647E.", "npc/metropolice/vo/control100percent.wav")
nut.voice.Register("combine", "Copy", "Copy.", "npc/metropolice/vo/copy.wav")
nut.voice.Register("combine", "Cover me", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav")
nut.voice.Register("combine", "CP is compromised", "CP is compromised! Re-establish!", "npc/metropolice/vo/cpiscompromised.wav")
nut.voice.Register("combine", "Report in", "CP requests all units' location report in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
nut.voice.Register("combine", "Defender", "Defender!", "npc/metropolice/vo/defender.wav")
nut.voice.Register("combine", "Destroy cover", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav")
nut.voice.Register("combine", "Distribution block", "Distribution block.", "npc/metropolice/vo/distributionblock.wav")
nut.voice.Register("combine", "Document", "Document.", "npc/metropolice/vo/document.wav")
nut.voice.Register("combine", "Don't move", "Don't move!", "npc/metropolice/vo/dontmove.wav")
nut.voice.Register("combine", "Eight", "Eight.", "npc/metropolice/vo/eight.wav")
nut.voice.Register("combine", "Eighteen", "Eighteen.", "npc/metropolice/vo/eighteen.wav")
nut.voice.Register("combine", "Eighty", "Eighty.", "npc/metropolice/vo/eighty.wav")
nut.voice.Register("combine", "Eleven", "Eleven.", "npc/metropolice/vo/eleven.wav")
nut.voice.Register("combine", "Examine", "Examine.", "npc/metropolice/vo/examine.wav")
nut.voice.Register("combine", "Fifteen", "Fifteen.", "npc/metropolice/vo/fifteen.wav")
nut.voice.Register("combine", "Fifty", "Fifty.", "npc/metropolice/vo/fifty.wav")
nut.voice.Register("combine", "Final verdict", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav")
nut.voice.Register("combine", "Final warning", "Final warning!", "npc/metropolice/vo/finalwarning.wav")
nut.voice.Register("combine", "Firing to expose", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav")
nut.voice.Register("combine", "First warning", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav")
nut.voice.Register("combine", "Five", "Five.", "npc/metropolice/vo/five.wav")
nut.voice.Register("combine", "Four", "Four.", "npc/metropolice/vo/four.wav")
nut.voice.Register("combine", "Fourteen", "Fourteen.", "npc/metropolice/vo/fourteen.wav")
nut.voice.Register("combine", "Fourty", "Fourty.", "npc/metropolice/vo/fourty.wav")
nut.voice.Register("combine", "Get that 11-44", "Get that 11-44 inbound, we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
nut.voice.Register("combine", "Get down", "Get down!", "npc/metropolice/vo/getdown.wav")
nut.voice.Register("combine", "Get out", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav")
nut.voice.Register("combine", "Take a look", "Going to take a look.", "npc/metropolice/vo/goingtotakealook.wav")
nut.voice.Register("combine", "got one here", "Got one accomplice here.", {"npc/metropolice/vo/gotoneaccomplicehere.wav", "npc/metropolice/vo/gotsuspect1here.wav"})
nut.voice.Register("combine", "Grenade", "Grenade!", "npc/metropolice/vo/grenade.wav")
nut.voice.Register("combine", "Help", "Help!", "npc/metropolice/vo/help.wav")
nut.voice.Register("combine", "Hero", "Hero.", "npc/metropolice/vo/hero.wav")
nut.voice.Register("combine", "he's running", "He's running!", "npc/metropolice/vo/hesrunning.wav")
nut.voice.Register("combine", "Up there", "He's up there!", "npc/metropolice/vo/hesupthere.wav")
nut.voice.Register("combine", "High priority", "High priority region.", "npc/metropolice/vo/highpriorityregion.wav")
nut.voice.Register("combine", "Hold it", "Hold it!", "npc/metropolice/vo/holdit.wav")
nut.voice.Register("combine", "Hold it right", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav")
nut.voice.Register("combine", "Hold this position", "Protection team, hold this position.", "npc/metropolice/vo/holdthisposition.wav")
nut.voice.Register("combine", "Industrial", "Industrial zone.", "npc/metropolice/vo/industrialzone.wav")
nut.voice.Register("combine", "Infection", "Infection.", "npc/metropolice/vo/infection.wav")
nut.voice.Register("combine", "Infested zone", "Infested zone.", "npc/metropolice/vo/infestedzone.wav")
nut.voice.Register("combine", "Inject", "Inject.", "npc/metropolice/vo/inject.wav")
nut.voice.Register("combine", "Inocculate", "Inocculate.", "npc/metropolice/vo/innoculate.wav")
nut.voice.Register("combine", "In position", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav")
nut.voice.Register("combine", "Intercede", "Intercede.", "npc/metropolice/vo/intercede.wav")
nut.voice.Register("combine", "Investigate", "Investigate.", "npc/metropolice/vo/investigate.wav")
nut.voice.Register("combine", "I said move along", "I said move alone!", "npc/metropolice/vo/Isaidmovealong.wav")
nut.voice.Register("combine", "Isolate", "Isolate!", "npc/metropolice/vo/isolate.wav")
nut.voice.Register("combine", "Issuing malcompliant", "Issueing malcompliant citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
nut.voice.Register("combine", "Got 408", "I've got a 408 here at location.", "npc/metropolice/vo/Ivegot408hereatlocation.wav")
nut.voice.Register("combine", "Jury", "Jury.", "npc/metropolice/vo/jury.wav")
nut.voice.Register("combine", "Keep moving", "Keep moving.", "npc/metropolice/vo/keepmoving.wav")
nut.voice.Register("combine", "King", "King.", "npc/metropolice/vo/king.wav")
nut.voice.Register("combine", "Privacy violator", "I've got a level 3 civil privacy violator here.", "npc/metropolice/vo/level3civilprivacyviolator.wav")
nut.voice.Register("combine", "Line", "Line!", "npc/metropolice/vo/line.wav")
nut.voice.Register("combine", "Location", "Location.", "npc/metropolice/vo/location.wav")
nut.voice.Register("combine", "Lock", "Lock!", "npc/metropolice/vo/lock.wav")
nut.voice.Register("combine", "Lock pos", "All units, lock your position.", "npc/metropolice/vo/lockyourposition.wav")
nut.voice.Register("combine", "Looking for trouble", "Looking for trouble?", "npc/metropolice/vo/lookingfortrouble.wav")
nut.voice.Register("combine", "Lookout", "Lookout!", "npc/metropolice/vo/lookout.wav")
nut.voice.Register("combine", "Loyalty check failed", "Parole, I have a failure to comply with loyalty check. Is it possible to 10-103 him?", "npc/metropolice/vo/loyaltycheckfailure.wav")
nut.voice.Register("combine", "Malcompliant", "Malcompliant 10-107 at my 10-20, preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav")
nut.voice.Register("combine", "Malignant", "Malignant.", "npc/metropolice/vo/malignant.wav")
nut.voice.Register("combine", "Meters", "Meters.", "npc/metropolice/vo/meters.wav")
nut.voice.Register("combine", "Minor hits", "Minor hits, continuing prosecution.", "npc/metropolice/vo/minorhitscontinuing.wav")
nut.voice.Register("combine", "Move", "Move.", "npc/metropolice/vo/move.wav")
nut.voice.Register("combine", "Move along", "Move along.", {"npc/metropolice/vo/movealong.wav", "npc/metropolice/vo/movealong3.wav"})
nut.voice.Register("combine", "Move back", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav")
nut.voice.Register("combine", "Move it", "Move it!", {"npc/metropolice/vo/moveit.wav", "npc/metropolice/vo/moveit2.wav"})
nut.voice.Register("combine", "Arrest position", "All units, move to arrest position.", "npc/metropolice/vo/movetoarrestpositions.wav")
nut.voice.Register("combine", "Moving to cover", "Moving to cover!", "npc/metropolice/vo/movingtocover.wav")
nut.voice.Register("combine", "Moving to hardpoint", "Moving to hardpoint.", {"npc/metropolice/vo/movingtohardpoint.wav", "npc/metropolice/vo/movingtohardpoint2.wav"})
nut.voice.Register("combine", "Necrotics", "Necrotics.", "npc/metropolice/vo/necrotics.wav")
nut.voice.Register("combine", "Need help", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
nut.voice.Register("combine", "Nine", "Nine.", "npc/metropolice/vo/nine.wav")
nut.voice.Register("combine", "Nineteen", "Nineteen.", "npc/metropolice/vo/nineteen.wav")
nut.voice.Register("combine", "Ninety", "Ninety.", "npc/metropolice/vo/ninety.wav")
nut.voice.Register("combine", "No contact", "No contact.", "npc/metropolice/vo/nocontact.wav")
nut.voice.Register("combine", "Noncitizen", "Non-citizen.", "npc/metropolice/vo/noncitizen.wav")
nut.voice.Register("combine", "Nonpatrol", "Non-patrol region.", "npc/metropolice/vo/nonpatrolregion.wav")
nut.voice.Register("combine", "Now get out", "Now get out of here.", "npc/metropolice/vo/nowgetoutofhere.wav")
nut.voice.Register("combine", "Officer down", "Officer down! Request all units Code-3 to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
nut.voice.Register("combine", "Need assistance", "Officer needs assistance. I am 11-99!", "npc/metropolice/vo/officerneedsassistance.wav")
nut.voice.Register("combine", "Needs help", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav")
nut.voice.Register("combine", "Under fire", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav")
nut.voice.Register("combine", "One", "One.", "npc/metropolice/vo/one.wav")
nut.voice.Register("combine", "One hundred", "One hundred.", "npc/metropolice/vo/onehundred.wav")
nut.voice.Register("combine", "Outbreak", "Outbreak.", "npc/metropolice/vo/outbreak.wav")
nut.voice.Register("combine", "Got biotic", "I got an outland biotic in here.", "npc/metropolice/vo/outlandbioticinhere.wav")
nut.voice.Register("combine", "Pacifying", "Pacifying.", "npc/metropolice/vo/pacifying.wav")
nut.voice.Register("combine", "Patrol", "Patrol!", "npc/metropolice/vo/patrol.wav")
nut.voice.Register("combine", "Pick up the can", "Pick up the can.", {"npc/metropolice/vo/pickupthecan1.wav", "npc/metropolice/vo/pickupthecan2.wav"})
nut.voice.Register("combine", "I said pick up", "I said pick up the can!", "npc/metropolice/vo/pickupthecan3.wav")
nut.voice.Register("combine", "Possible 404", "Possible 404 here.", "npc/metropolice/vo/possible404here.wav")
nut.voice.Register("combine", "Civil judgement", "Suspect, prepare to receive civil judgement!", "npc/metropolice/vo/prepareforjudgement.wav")
nut.voice.Register("combine", "Preserve", "Preserve.", "npc/metropolice/vo/preserve.wav")
nut.voice.Register("combine", "Pressure", "Pressure.", "npc/metropolice/vo/pressure.wav")
nut.voice.Register("combine", "priority two", "I got a priority 2 anti-citizen here.", "npc/metropolice/vo/priority2anticitizenhere.wav")
nut.voice.Register("combine", "proceed to cp", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav")
nut.voice.Register("combine", "Production block", "Production block.", "npc/metropolice/vo/productionblock.wav")
nut.voice.Register("combine", "Prosecute", "Prosecute.", "npc/metropolice/vo/prosecute.wav")
nut.voice.Register("combine", "Protection complete", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav")
nut.voice.Register("combine", "Put in trash", "Put it in the trash can.", {"npc/metropolice/vo/putitinthetrash1.wav", "npc/metropolice/vo/putitinthetrash2.wav"})
nut.voice.Register("combine", "Quick", "Quick.", "npc/metropolice/vo/quick.wav")
nut.voice.Register("combine", "Ready to amputate", "Ready to amputate.", "npc/metropolice/vo/readytoamputate.wav")
nut.voice.Register("combine", "Ready to judge", "Ready to judge.", "npc/metropolice/vo/readytojudge.wav")
nut.voice.Register("combine", "Ready to prosecute", "Ready to prosecute.", "npc/metropolice/vo/readytoprosecute.wav")
nut.voice.Register("combine", "Final warning issued", "Ready to prosecute malcompliant citizen, final warning issued.", "npc/metropolice/vo/readytoprosecutefinalwarning.wav")
nut.voice.Register("combine", "Code 3", "Reinforcement team, code 3!", "npc/metropolice/vo/reinforcementteamscode3.wav")
nut.voice.Register("combine", "Residential", "Residential block.", "npc/metropolice/vo/residentialblock.wav")
nut.voice.Register("combine", "Responding", "Responding.", "npc/metropolice/vo/responding2.wav")
nut.voice.Register("combine", "Restrict", "Restrict!", "npc/metropolice/vo/restrict.wav")
nut.voice.Register("combine", "Restricted block", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav")
nut.voice.Register("combine", "Rodger", "Rodger that.", "npc/metropolice/vo/rodgerthat.wav")
nut.voice.Register("combine", "Rodger that", "Rodger that.", "npc/metropolice/vo/rodgerthat.wav")
nut.voice.Register("combine", "Roller", "Roller.", "npc/metropolice/vo/roller.wav")
nut.voice.Register("combine", "Search", "Search!", "npc/metropolice/vo/search.wav")
nut.voice.Register("combine", "Searching for", "Searching for suspect.", "npc/metropolice/vo/searchingforsuspect.wav")
nut.voice.Register("combine", "Second warning", "Second warning.", "npc/metropolice/vo/secondwarning.wav")
nut.voice.Register("combine", "Sector", "Sector.", "npc/metropolice/vo/sector.wav")
nut.voice.Register("combine", "Sentence delivered", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav")
nut.voice.Register("combine", "Serve", "Serve.", "npc/metropolice/vo/serve.wav")
nut.voice.Register("combine", "Seven", "Seven.", "npc/metropolice/vo/seven.wav")
nut.voice.Register("combine", "Seventeen", "Seventeen.", "npc/metropolice/vo/seventeen.wav")
nut.voice.Register("combine", "Seventy", "Seventy.", "npc/metropolice/vo/seventy.wav")
nut.voice.Register("combine", "Shit", "Shit!", "npc/metropolice/vo/shit.wav")
nut.voice.Register("combine", "Shots fired", "Shots fired, hostile malignants here.", "npc/metropolice/vo/shotsfiredhostilemalignants.wav")
nut.voice.Register("combine", "Six", "Six.", "npc/metropolice/vo/six.wav")
nut.voice.Register("combine", "Sixteen", "Sixteen.", "npc/metropolice/vo/sixteen.wav")
nut.voice.Register("combine", "Sixty", "Sixty.", "npc/metropolice/vo/sixty.wav")
nut.voice.Register("combine", "Sociocide", "Sociocide.", "npc/metropolice/vo/sociocide.wav")
nut.voice.Register("combine", "Standard loyalty check", "Rodger that, I'm going to run a standard loyalty check prodecure 243 at my 10-20, over.", "npc/metropolice/vo/standardloyaltycheck.wav")
nut.voice.Register("combine", "Sterelize", "Sterelize.", "npc/metropolice/vo/sterilize.wav")
nut.voice.Register("combine", "Stick", "Stick.", "npc/metropolice/vo/stick.wav")
nut.voice.Register("combine", "Subject", "Subject.", "npc/metropolice/vo/subject.wav")
nut.voice.Register("combine", "Location unknown", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav")
nut.voice.Register("combine", "Suspend", "Suspend.", "npc/metropolice/vo/suspend.wav")
nut.voice.Register("combine", "Sweeping for", "Sweeping for suspect.", "npc/metropolice/vo/sweepingforsuspect.wav")
nut.voice.Register("combine", "Take cover", "Take cover!", "npc/metropolice/vo/takecover.wav")
nut.voice.Register("combine", "Tap", "Tap.", "npc/metropolice/vo/tap.wav")
nut.voice.Register("combine", "Team in position", "Team in position, advance!", "npc/metropolice/vo/teaminpositionadvance.wav")
nut.voice.Register("combine", "Ten", "Ten.", "npc/metropolice/vo/ten.wav")
nut.voice.Register("combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav")
nut.voice.Register("combine", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav")
nut.voice.Register("combine", "10-8 standing by", "10-8, Standing by.", {"npc/metropolice/vo/ten8standingby.wav", "npc/metropolice/vo/unitis10-8standingby.wav"})
nut.voice.Register("combine", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav")
nut.voice.Register("combine", "Terminal restriction", "Terminal restriction zone.", "npc/metropolice/vo/terminalrestrictionzone.wav")
nut.voice.Register("combine", "That's a grenade", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav")
nut.voice.Register("combine", "There he is", "There he is!", "npc/metropolice/vo/thereheis.wav")
nut.voice.Register("combine", "Thirteen", "Thirteen.", "npc/metropolice/vo/thirteen.wav")
nut.voice.Register("combine", "Thirty", "Thirty.", "npc/metropolice/vo/thirty.wav")
nut.voice.Register("combine", "Three hundred", "Three hundred.", "npc/metropolice/vo/threehundred.wav")
nut.voice.Register("combine", "Three", "Three.", "npc/metropolice/vo/three.wav")
nut.voice.Register("combine", "Transit block", "Transit block.", "npc/metropolice/vo/transitblock.wav")
nut.voice.Register("combine", "Twelve", "Twelve.", "npc/metropolice/vo/twelve.wav")
nut.voice.Register("combine", "Twenty", "Twenty.", "npc/metropolice/vo/twenty.wav")
nut.voice.Register("combine", "Two", "Two.", "npc/metropolice/vo/two.wav")
nut.voice.Register("combine", "Two hundred", "Two hundred.", "npc/metropolice/vo/twohundred.wav")
nut.voice.Register("combine", "Union", "Union.", "npc/metropolice/vo/union.wav")
nut.voice.Register("combine", "10-65", "Unit is 10-65.", "npc/metropolice/vo/unitis10-65.wav")
nut.voice.Register("combine", "10-8", "Unit is on duty, 10-8.", "npc/metropolice/vo/unitisonduty10-8.wav")
nut.voice.Register("combine", "Unlawful entry", "603, Unlawful entry.", "npc/metropolice/vo/unlawfulentry603.wav")
nut.voice.Register("combine", "UPI", "U.P.I.", "npc/metropolice/vo/upi.wav")
nut.voice.Register("combine", "Vacate citizen", "Vacate, citizen.", "npc/metropolice/vo/vacatecitizen.wav")
nut.voice.Register("combine", "Vice", "Vice.", "npc/metropolice/vo/vice.wav")
nut.voice.Register("combine", "Victor", "Victor.", "npc/metropolice/vo/victor.wav")
nut.voice.Register("combine", "Watch it", "Watch it!", "npc/metropolice/vo/watchit.wav")
nut.voice.Register("combine", "We are social stable", "We are social stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav")
nut.voice.Register("combine", "X-Ray", "X-Ray.", "npc/metropolice/vo/xray.wav")
nut.voice.Register("combine", "Yellow", "Yellow.", "npc/metropolice/vo/yellow.wav")
nut.voice.Register("combine", "You knocked it", "You knocked it over. Pick it up.", "npc/metropolice/vo/youknockeditover.wav")
nut.voice.Register("combine", "Malcompliance verdict", "You want a malcompliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav")
nut.voice.Register("combine", "Zero", "Zero.", "npc/metropolice/vo/zero.wav")
nut.voice.Register("combine", "Zone", "Zone.", "npc/metropolice/vo/zone.wav")
nut.voice.Register("combine", "Antiseptic", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav")
nut.voice.Register("combine", "Apex", "Apex.", "npc/combine_soldier/vo/apex.wav")
nut.voice.Register("combine", "Blade", "Blade.", "npc/combine_soldier/vo/blade.wav")
nut.voice.Register("combine", "Boomer", "Boomer.", "npc/combine_soldier/vo/boomer.wav")
nut.voice.Register("combine", "Cleaned", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav")
nut.voice.Register("combine", "Closing", "Closing.", {"npc/combine_soldier/vo/closing.wav", "npc/combine_soldier/vo/closing2.wav"})
nut.voice.Register("combine", "Sector not steril", "Confired sector not sterile.", "npc/combine_soldier/vo/confirmsectornotsterile.wav")
nut.voice.Register("combine", "Contact", "Contact.", "npc/combine_soldier/vo/contact.wav")
nut.voice.Register("combine", "Contained", "Contained.", "npc/combine_soldier/vo/contained.wav")
nut.voice.Register("combine", "Copy that", "Copy that.", "npc/combine_soldier/vo/copythat.wav")
nut.voice.Register("combine", "Cover", "Cover.", "npc/combine_soldier/vo/coverhurt.wav")
nut.voice.Register("combine", "Dagger", "Dagger.", "npc/combine_soldier/vo/dagger.wav")
nut.voice.Register("combine", "Dash", "Dash.", "npc/combine_soldier/vo/dash.wav")
nut.voice.Register("combine", "Echo", "Echo.", "npc/combine_soldier/vo/echo.wav")
nut.voice.Register("combine", "Engaging", "Engaging.", "npc/combine_soldier/vo/engaging.wav")
nut.voice.Register("combine", "Fist", "Fist.", "npc/combine_soldier/vo/fist.wav")
nut.voice.Register("combine", "Flash", "Flash.", "npc/combine_soldier/vo/flash.wav")
nut.voice.Register("combine", "Flatline", "Flatline.", "npc/combine_soldier/vo/flatline.wav")
nut.voice.Register("combine", "Flush", "Flush.", "npc/combine_soldier/vo/flush.wav")
nut.voice.Register("combine", "Ghost", "Ghost.", "npc/combine_soldier/vo/ghost.wav")
nut.voice.Register("combine", "Go sharp", "Go sharp.", "npc/combine_soldier/vo/gosharp.wav")
nut.voice.Register("combine", "Grid", "Grid.", "npc/combine_soldier/vo/grid.wav")
nut.voice.Register("combine", "Hammer", "Hammer.", "npc/combine_soldier/vo/hammer.wav")
nut.voice.Register("combine", "Helix", "Helix.", "npc/combine_soldier/vo/helix.wav")
nut.voice.Register("combine", "Hunter", "Hunter.", "npc/combine_soldier/vo/hunter.wav")
nut.voice.Register("combine", "Hurricane", "Hurricane.", "npc/combine_soldier/vo/hurricane.wav")
nut.voice.Register("combine", "Ice", "Ice.", "npc/combine_soldier/vo/ice.wav")
nut.voice.Register("combine", "Inbound", "Inbound.", "npc/combine_soldier/vo/inbound.wav")
nut.voice.Register("combine", "Infected", "Infected.", "npc/combine_soldier/vo/infected.wav")
nut.voice.Register("combine", "Ion", "Ion.", "npc/combine_soldier/vo/ion.wav")
nut.voice.Register("combine", "Jet", "Jet.", "npc/combine_soldier/vo/jet.wav")
nut.voice.Register("combine", "Judge", "Judge.", "npc/combine_soldier/vo/judge.wav")
nut.voice.Register("combine", "Kilo", "Kilo.", "npc/combine_soldier/vo/kilo.wav")
nut.voice.Register("combine", "Leader", "Leader.", "npc/combine_soldier/vo/leader.wav")
nut.voice.Register("combine", "Lost contact", "Lost contact.", "npc/combine_soldier/vo/lostcontact.wav")
nut.voice.Register("combine", "Mace", "Mace.", "npc/combine_soldier/vo/mace.wav")
nut.voice.Register("combine", "Move in", "Move in!", "npc/combine_soldier/vo/movein.wav")
nut.voice.Register("combine", "Nomad", "Nomad.", "npc/combine_soldier/vo/nomad.wav")
nut.voice.Register("combine", "Nova", "Nova.", "npc/combine_soldier/vo/nova.wav")
nut.voice.Register("combine", "Outbreak", "Outbreak.", "npc/combine_soldier/vo/outbreak.wav")
nut.voice.Register("combine", "Overwatch", "Overwatch.", "npc/combine_soldier/vo/overwatch.wav")
nut.voice.Register("combine", "Payback", "Payback.", "npc/combine_soldier/vo/payback.wav")
nut.voice.Register("combine", "Phantom", "Phantom.", "npc/combine_soldier/vo/phantom.wav")
nut.voice.Register("combine", "Prosecuting", "Prosecuting.", "npc/combine_soldier/vo/procecuting.")
nut.voice.Register("combine", "Quicksand", "Quicksand.", "npc/combine_soldier/vo/quicksand.wav")
nut.voice.Register("combine", "Range", "Range.", "npc/combine_soldier/vo/range.wav")
nut.voice.Register("combine", "Ranger", "Ranger.", "npc/combine_soldier/vo/ranger.wav")
nut.voice.Register("combine", "Razor", "Razor.", "npc/combine_soldier/vo/razor.wav")
nut.voice.Register("combine", "Ready weapons", "Ready weapons.", "npc/combine_soldier/vo/readyweapons.wav")
nut.voice.Register("combine", "Ready charges", "Ready charges.", "npc/combine_soldier/vo/readycharges.wav")
nut.voice.Register("combine", "Reaper", "Reaper.", "npc/combine_soldier/vo/reaper.wav")
nut.voice.Register("combine", "Clear", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav")
nut.voice.Register("combine", "Ripcord", "Ripcord.", "npc/combine_soldier/vo/ripcord.wav")
nut.voice.Register("combine", "Savage", "Savage.", "npc/combine_soldier/vo/savage.wav")
nut.voice.Register("combine", "Scar", "Scar.", "npc/combine_soldier/vo/scar.wav")
nut.voice.Register("combine", "Sector not secure", "Sector is now secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
nut.voice.Register("combine", "Secure", "Secure.", "npc/combine_soldier/vo/secure.wav")
nut.voice.Register("combine", "Shadow", "Shadow.", "npc/combine_soldier/vo/shadow.wav")
nut.voice.Register("combine", "Sharpzone", "Sharpzone.", "npc/combine_soldier/vo/sharpzone.wav")
nut.voice.Register("combine", "Slam", "Slam.", "npc/combine_soldier/vo/slam.wav")
nut.voice.Register("combine", "Slash", "Slash.", "npc/combine_soldier/vo/slash.wav")
nut.voice.Register("combine", "Spear", "Spear.", "npc/combine_soldier/vo/spear.wav")
nut.voice.Register("combine", "Stab", "Stab.", "npc/combine_soldier/vo/stab.wav")
nut.voice.Register("combine", "Team holding", "Stabilization team holding in position.", "npc/combine_soldier/vo/stabilizationteamholding.wav")
nut.voice.Register("combine", "Standing by", "Standing by.", "npc/combine_soldier/vo/standingby].wav")
nut.voice.Register("combine", "Star", "Star.", "npc/combine_soldier/vo/star.wav")
nut.voice.Register("combine", "Stay alert", "Stay alert.", "npc/combine_soldier/vo/stayalert.wav")
nut.voice.Register("combine", "Stinger", "Stinger.", "npc/combine_soldier/vo/stringer.wav")
nut.voice.Register("combine", "Storm", "Storm.", "npc/combine_soldier/vo/storm.wav")
nut.voice.Register("combine", "Strike", "Striker.", "npc/combine_soldier/vo/striker.wav")
nut.voice.Register("combine", "Sundown", "Sundown.", "npc/combine_soldier/vo/sundown.wav")
nut.voice.Register("combine", "Sweeper", "Sweeper.", "npc/combine_soldier/vo/sweeper.wav")
nut.voice.Register("combine", "Sweeping in", "Sweeping in.", "npc/combine_soldier/vo/sweepingin.wav")
nut.voice.Register("combine", "Swift", "Swift.", "npc/combine_soldier/vo/swift.wav")
nut.voice.Register("combine", "Sword", "Sword.", "npc/combine_soldier/vo/sword.wav")
nut.voice.Register("combine", "Target", "Target.", "npc/combine_soldier/vo/target.wav")
nut.voice.Register("combine", "Wrap it up", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav")
nut.voice.Register("combine", "Tracker", "Tracker.", "npc/combine_soldier/vo/tracker.wav")
nut.voice.Register("combine", "Uniform", "Uniform.", "npc/combine_soldier/vo/uniform.wav")
nut.voice.Register("combine", "Unit is inbound", "Unit is inbound.", "npc/combine_soldier/vo/unitisinbound.wav")
nut.voice.Register("combine", "Unit is moving in", "Unit is moving in.", "npc/combine_soldier/vo/unitismovingin.wav")
nut.voice.Register("combine", "Vamp", "Vamp.", "npc/combine_soldier/vo/vamp.wav")
nut.voice.Register("combine", "Viscon", "Viscon.", "npc/combine_soldier/vo/viscon.wav")
nut.voice.Register("combine", "Winder", "Winder.", "npc/combine_soldier/vo/winder.wav")
nut.voice.Register("combine", "Visual on exogen", "Visual on exogen.", "npc/combine_soldier/vo/visualonexogen.wav")

-- Dispatch voices.
nut.voice.Register("dispatch", "Anti-citizen report", "Attention ground units, anti-citizen reported in this community. Code: LOCK, CAUTERIZE, STABILIZE.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav")
nut.voice.Register("dispatch", "Anti-civil activity", "Protection team alert, evidence of anti-civil activity in this community. Code: ASSEMBLE, CLAMP, CONTAIN.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav")
nut.voice.Register("dispatch", "Capital malcompliance", "Individual, you are charged with capital malcompliance. Anti-citizen status approved.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav")
nut.voice.Register("dispatch", "Level Five", "Individual, you are now charged with socio-endangerment level five. Cease evasion immediately, receive your verdict.", "npc/overwatch/cityvoice/f_ceaseevasionlevelfive_spkr.wav")
nut.voice.Register("dispatch", "Citizenship revoked", "Individual, you are convicted of multi anti-civil violation. Implicit citizenship revoked. Status: MALIGNANT.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav")
nut.voice.Register("dispatch", "Confirm civil status", "Attention please, unidentified person of interest, confirm your civil status with local protection team immediately.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav")
nut.voice.Register("dispatch", "Evasion behavior", "Attention please, evasion behavior consistent with malcompliance. Ground protection team, alert. Code: ISOLATE, EXPOSE, ADMINISTER.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav")
nut.voice.Register("dispatch", "Inaction is conspiracy", "Citizen reminder, inaction is conspiracy. Report counter-behavior to a civil protection team immediately.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav")
nut.voice.Register("dispatch", "Local unrest", "Alert community ground protection unit, local unrest structure detected. ASSEMBLE. ADMINISTER. PACIFY.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav")
nut.voice.Register("dispatch", "Status evasion in progress", "Attention protection team, status evasion in progress in this community. RESPOND. ISOLATE. INQUIRE.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav")
nut.voice.Register("dispatch", "Autonomous judgement", "Attention all ground protection teams, autonomous judgement is now in effect. Sentencing is now discretionary. Code: AMPUTATE, ZERO, CONFIRM.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav")
nut.voice.Register("dispatch", "Judgement waiver", "Attention all ground protection teams, judgement waiver is now in effect. Capital prosecution is discretionary.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav")
nut.voice.Register("dispatch", "Rations deducted", "Attention occupants, your block is now charged with permisive inactive coersion. Five ration units deducted.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav")
nut.voice.Register("dispatch", "Level One", "Individual, you are charged with socio-endangerment level one. Protection units, prosecution code: DUTY, SWORD, MIDNIGHT.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav")
nut.voice.Register("dispatch", "Priority identification", "Citizen notice, priority identification check in progress. Please assemble in your designated inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav")
nut.voice.Register("dispatch", "Assume inspection position", "Attention please, all citizens in local residential block assume your inspection position.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav")
nut.voice.Register("dispatch", "Miscount detected", "Attention residents, miscount detected in your block. Cooperation with your civil protection team permits full ration reward.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav")
nut.voice.Register("dispatch", "Civil infection", "Attention residents, this block contains potential civil infection. Inform. Cooperate. Assemble.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav")