--[[
	Define your voice classes here. The function goes:

	nut.voice.defineClass(class, onCheck(client)[, onModify(client, sounds)])

	Class is the same class that starts the nut.voice.register
	It is case-insensitive. The onCheck passes the player trying
	to use the class. Return true to allow them to use the class.
--]]

-- What type of chat modes support voice commands:
nut.voice.chatTypes["ic"] = true
nut.voice.chatTypes["w"] = true
nut.voice.chatTypes["y"] = true
nut.voice.chatTypes["radio"] = true
nut.voice.chatTypes["dispatch"] = true

nut.voice.defineClass("combine", function(client)
	return client:isCombine()
end, function(client, sounds, chatType)
	if (chatType == "dispatch" or client:isCombineRank("SCN")) then
		return false
	end

	local beeps = SCHEMA.beepSounds[client:Team()] or SCHEMA.beepSounds[FACTION_CP]

	table.insert(sounds, 1, {(table.Random(beeps.on)), 0.25})
	sounds[#sounds + 1] = {(table.Random(beeps.off)), nil, 0.25}
end)

nut.voice.defineClass("dispatch", function(client)
	return SCHEMA:isDispatch(client)
end, function(client, sounds, chatType)
	if (chatType != "dispatch") then
		return false
	end
end, true)

--[[

-- Example of citizen class that requires the ciitzen to have 'y' flag.
nut.voice.defineClass("citizen", function(client)
	return client:getChar():hasFlags("y")

end)
--]]

nut.voice.register("combine", "0", "Zero.", "npc/metropolice/vo/zero.wav")
nut.voice.register("combine", "1", "One.", "npc/metropolice/vo/one.wav")
nut.voice.register("combine", "10", "Ten.", "npc/metropolice/vo/ten.wav")
nut.voice.register("combine", "10-0 HUNTING", "10-0, 10-0, viscerator is hunting!", "npc/metropolice/vo/tenzerovisceratorishunting.wav")
nut.voice.register("combine", "100", "One-hundred.", "npc/metropolice/vo/onehundred.wav")
nut.voice.register("combine", "10-103 TAG", "Possible 10-103, my location, alert TAG units.", "npc/metropolice/vo/possible10-103alerttagunits.wav")
nut.voice.register("combine", "10-107", "I have a 10-107 here, send AirWatch for tag.", "npc/metropolice/vo/gota10-107sendairwatch.wav")
nut.voice.register("combine", "10-108", "We have a 10-108!", "npc/metropolice/vo/wehavea10-108.wav")
nut.voice.register("combine", "10-14", "Holding on 10-14 duty, eh, code four.", "npc/metropolice/vo/holdingon10-14duty.wav")
nut.voice.register("combine", "10-15", "Prepare for 10-15.", "npc/metropolice/vo/preparefor1015.wav")
nut.voice.register("combine", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav")
nut.voice.register("combine", "10-25", "Any unit, report in with 10-25 as suspect.", "npc/metropolice/vo/unitreportinwith10-25suspect.wav")
nut.voice.register("combine", "10-30", "I have a 10-30, my 10-20, responding, code two.", "npc/metropolice/vo/Ihave10-30my10-20responding.wav")
nut.voice.register("combine", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav")
nut.voice.register("combine", "10-65", "Unit is 10-65.", "npc/metropolice/vo/unitis10-65.wav")
nut.voice.register("combine", "10-78", "Dispatch, I need 10-78, officer in trouble!", "npc/metropolice/vo/dispatchIneed10-78.wav")
nut.voice.register("combine", "10-8 standing by", "10-8, standing by.", "npc/metropolice/vo/ten8standingby.wav")
nut.voice.register("combine", "10-8", "Unit is on-duty, 10-8.", "npc/metropolice/vo/unitisonduty10-8.wav")
nut.voice.register("combine", "10-91D", "10-91d count is...", "npc/metropolice/vo/ten91dcountis.wav")
nut.voice.register("combine", "10-97 GOA", "10-97, that suspect is GOA.", "npc/metropolice/vo/ten97suspectisgoa.wav")
nut.voice.register("combine", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav")
nut.voice.register("combine", "10-99", "Officer down, I am 10-99, I repeat, I am 10-99!", "npc/metropolice/vo/officerdownIam10-99.wav")
nut.voice.register("combine", "11-44", "Get that 11-44 inbound, we're cleaning up now.", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
nut.voice.register("combine", "11-6", "Suspect 11-6, my 10-20 is...", "npc/metropolice/vo/suspect11-6my1020is.wav")
nut.voice.register("combine", "11-99", "11-99, officer needs assistance!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
nut.voice.register("combine", "2", "Two.", "npc/metropolice/vo/two.wav")
nut.voice.register("combine", "20", "Twenty.", "npc/metropolice/vo/twenty.wav")
nut.voice.register("combine", "200", "Two-hundred.", "npc/metropolice/vo/twohundred.wav")
nut.voice.register("combine", "3", "Three.", "npc/metropolice/vo/three.wav")
nut.voice.register("combine", "30", "Thirty.", "npc/metropolice/vo/thirty.wav")
nut.voice.register("combine", "300", "Three-hundred.", "npc/metropolice/vo/threehundred.wav")
nut.voice.register("combine", "34S AT", "All units, BOL, we have 34-S at...", "npc/metropolice/vo/allunitsbol34sat.wav")
nut.voice.register("combine", "4", "Four.", "npc/metropolice/vo/four.wav")
nut.voice.register("combine", "40", "Fourty.", "npc/metropolice/vo/fourty.wav")
nut.voice.register("combine", "404", "404 zone.", "npc/metropolice/vo/404zone.wav")
nut.voice.register("combine", "408", "I've got a 408 here at location.", "npc/metropolice/vo/Ivegot408hereatlocation.wav")
nut.voice.register("combine", "415B", "Is 415b.", "npc/metropolice/vo/is415b.wav")
nut.voice.register("combine", "5", "Five.", "npc/metropolice/vo/five.wav")
nut.voice.register("combine", "50", "Fifty.", "npc/metropolice/vo/fifty.wav")
nut.voice.register("combine", "505", "Dispatch, we need AirWatch, subject is 505!", "npc/metropolice/vo/airwatchsubjectis505.wav")
nut.voice.register("combine", "6", "Six.", "npc/metropolice/vo/six.wav")
nut.voice.register("combine", "60", "Sixty.", "npc/metropolice/vo/sixty.wav")
nut.voice.register("combine", "603", "603, unlawful entry.", "npc/metropolice/vo/unlawfulentry603.wav")
nut.voice.register("combine", "63", "63, criminal trespass.", "npc/metropolice/vo/criminaltrespass63.wav")
nut.voice.register("combine", "7", "Seven.", "npc/metropolice/vo/seven.wav")
nut.voice.register("combine", "70", "Seventy.", "npc/metropolice/vo/seventy.wav")
nut.voice.register("combine", "8", "Eight.", "npc/metropolice/vo/eight.wav")
nut.voice.register("combine", "80", "Eighty.", "npc/metropolice/vo/eighty.wav")
nut.voice.register("combine", "9", "Nine.", "npc/metropolice/vo/nine.wav")
nut.voice.register("combine", "90", "Ninety.", "npc/metropolice/vo/ninety.wav")
nut.voice.register("combine", "THAT'S A GRENADE", "That's a grenade!", "npc/metropolice/vo/thatsagrenade.wav")
nut.voice.register("combine", "ACQUIRING", "Acquiring on visual!", "npc/metropolice/vo/acquiringonvisual.wav")
nut.voice.register("combine", "ADMINISTER", "Administer.", "npc/metropolice/vo/administer.wav")
nut.voice.register("combine", "CONFIRMED ADW", "Confirmed as ADW on that suspect, 10-0.", "npc/metropolice/vo/confirmadw.wav")
nut.voice.register("combine", "AFFIRMATIVE", "Affirmative.", "npc/metropolice/vo/affirmative.wav")
nut.voice.register("combine", "ALL UNITS MOVE", "All units, move in!", "npc/metropolice/vo/allunitsmovein.wav")
nut.voice.register("combine", "AMPUTATE", "Amputate.", "npc/metropolice/vo/amputate.wav")
nut.voice.register("combine", "ANTICITIZEN", "Anti-citizen.", "npc/metropolice/vo/anticitizen.wav")
nut.voice.register("combine", "ANTISEPTIC", "Antiseptic.", "npc/combine_soldier/vo/antiseptic.wav")
nut.voice.register("combine", "APEX", "Apex.", "npc/combine_soldier/vo/apex.wav")
nut.voice.register("combine", "APPLY", "Apply.", "npc/metropolice/vo/apply.wav")
nut.voice.register("combine", "ARREST POSITIONS", "All units, move to arrest positions!", "npc/metropolice/vo/movetoarrestpositions.wav")
nut.voice.register("combine", "AT CHECKPOINT", "At checkpoint.", "npc/metropolice/vo/atcheckpoint.wav")
nut.voice.register("combine", "AT LOCATION REPORT", "Protection-teams at location, report in.", "npc/metropolice/vo/ptatlocationreport.wav")
nut.voice.register("combine", "BACK ME UP", "Back me up, I'm out!", "npc/metropolice/vo/backmeupImout.wav")
nut.voice.register("combine", "BACKUP", "Backup!", "npc/metropolice/vo/backup.wav")
nut.voice.register("combine", "BLADE", "Blade.", "npc/combine_soldier/vo/blade.wav")
nut.voice.register("combine", "BLEEDING", "Suspect is bleeding from multiple wounds!", "npc/metropolice/vo/suspectisbleeding.wav")
nut.voice.register("combine", "BLIP", "Catch that blip on the stabilization readout?", "npc/metropolice/vo/catchthatbliponstabilization.wav")
nut.voice.register("combine", "BLOCK HOLDING", "Block is holding, cohesive.", "npc/metropolice/vo/blockisholdingcohesive.wav")
nut.voice.register("combine", "BLOCK", "Block!", "npc/metropolice/vo/block.wav")
nut.voice.register("combine", "BOL 243", "CP, we need AirWatch to BOL for that 243.", "npc/metropolice/vo/cpbolforthat243.wav")
nut.voice.register("combine", "BOOMER", "Boomer.", "npc/combine_soldier/vo/boomer.wav")
nut.voice.register("combine", "BREAK COVER", "Break his cover!", "npc/metropolice/vo/breakhiscover.wav")
nut.voice.register("combine", "CAN1", "Pick up that can.", "npc/metropolice/vo/pickupthecan1.wav")
nut.voice.register("combine", "CAN2", "Pick up the can!", "npc/metropolice/vo/pickupthecan2.wav")
nut.voice.register("combine", "CAN3", "I said, pick up the can!", "npc/metropolice/vo/pickupthecan3.wav")
nut.voice.register("combine", "CAN4", "Now, put it in the trash-can.", "npc/metropolice/vo/putitinthetrash1.wav")
nut.voice.register("combine", "CAN5", "I said, put it in the trash-can!", "npc/metropolice/vo/putitinthetrash2.wav")
nut.voice.register("combine", "CAN6", "You knocked it over, pick it up!", "npc/metropolice/vo/youknockeditover.wav")
nut.voice.register("combine", "CANAL", "Canal.", "npc/metropolice/vo/canal.wav")
nut.voice.register("combine", "CANALBLOCK", "Canalblock!", "npc/metropolice/vo/canalblock.wav")
nut.voice.register("combine", "CAUTERIZE", "Cauterize.", "npc/metropolice/vo/cauterize.wav")
nut.voice.register("combine", "CHECK MISCOUNT", "Check for miscount.", "npc/metropolice/vo/checkformiscount.wav")
nut.voice.register("combine", "CHECKPOINTS", "Proceed to designated checkpoints.", "npc/metropolice/vo/proceedtocheckpoints.wav")
nut.voice.register("combine", "CITIZEN SUMMONED", "Reporting citizen summoned into voluntary conscription for channel open service detail T94-332.", "npc/metropolice/vo/citizensummoned.wav")
nut.voice.register("combine", "CITIZEN", "Citizen.", "npc/metropolice/vo/citizen.wav")
nut.voice.register("combine", "CLASSIFY DB", "Classify subject name as 'DB'; this block ready for clean-out.", "npc/metropolice/vo/classifyasdbthisblockready.wav")
nut.voice.register("combine", "CLEANED", "Cleaned.", "npc/combine_soldier/vo/cleaned.wav")
nut.voice.register("combine", "CLEAR CODE 100", "Clear and code one-hundred.", "npc/metropolice/vo/clearandcode100.wav")
nut.voice.register("combine", "CLOSE ON SUSPECT", "All units, close on suspect!", "npc/metropolice/vo/allunitscloseonsuspect.wav")
nut.voice.register("combine", "CLOSING", "Closing!", {"npc/combine_soldier/vo/closing.wav", "npc/combine_soldier/vo/closing2.wav"})
nut.voice.register("combine", "CODE 100", "Code one-hundred.", "npc/metropolice/vo/code100.wav")
nut.voice.register("combine", "CODE 2", "All units, code two!", "npc/metropolice/vo/allunitscode2.wav")
nut.voice.register("combine", "CODE 3", "Officer down, request all units, code three to my 10-20!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
nut.voice.register("combine", "CODE 7", "Code seven.", "npc/metropolice/vo/code7.wav")
nut.voice.register("combine", "CONDEMNED", "Condemned zone!", "npc/metropolice/vo/condemnedzone.wav")
nut.voice.register("combine", "CONTACT 243", "Contact with 243 suspect, my 10-20 is...", "npc/metropolice/vo/contactwith243suspect.wav")
nut.voice.register("combine", "CONTACT PRIORITY", "I have contact with a priority two!", "npc/metropolice/vo/contactwithpriority2.wav")
nut.voice.register("combine", "CONTACT", "Contact!", "npc/combine_soldier/vo/contact.wav")
nut.voice.register("combine", "CONTAINED", "Contained.", "npc/combine_soldier/vo/contained.wav")
nut.voice.register("combine", "CONTROL 100", "Control is one-hundred percent this location, no sign of that 647-E.", "npc/metropolice/vo/control100percent.wav")
nut.voice.register("combine", "CONTROLSECTION", "Control-section!", "npc/metropolice/vo/controlsection.wav")
nut.voice.register("combine", "CONVERGING", "Converging.", "npc/metropolice/vo/converging.wav")
nut.voice.register("combine", "COPY THAT", "Copy that.", "npc/combine_soldier/vo/copythat.wav")
nut.voice.register("combine", "COPY", "Copy.", "npc/metropolice/vo/copy.wav")
nut.voice.register("combine", "COVER", "Cover!", "npc/combine_soldier/vo/coverhurt.wav")
nut.voice.register("combine", "CP COMPROMISED", "CP is compromised, re-establish!", "npc/metropolice/vo/cpiscompromised.wav")
nut.voice.register("combine", "CP ESTABLISH", "CP, we need to establish our perimeter at...", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav")
nut.voice.register("combine", "CP OVERRUN", "CP is overrun, we have no containment!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav")
nut.voice.register("combine", "DAGGER", "Dagger.", "npc/combine_soldier/vo/dagger.wav")
nut.voice.register("combine", "DASH", "Dash.", "npc/combine_soldier/vo/dash.wav")
nut.voice.register("combine", "DB COUNT", "DB count is...", "npc/metropolice/vo/dbcountis.wav")
nut.voice.register("combine", "DEFENDER", "Defender!", "npc/metropolice/vo/defender.wav")
nut.voice.register("combine", "DESERVICED AREA", "Deserviced area.", "npc/metropolice/vo/deservicedarea.wav")
nut.voice.register("combine", "DESIGNATE SUSPECT", "Designate suspect as...", "npc/metropolice/vo/designatesuspectas.wav")
nut.voice.register("combine", "DESTROY COVER", "Destroy that cover!", "npc/metropolice/vo/destroythatcover.wav")
nut.voice.register("combine", "DISLOCATE INTERPOSE", "Fire to dislocate that interpose!", "npc/metropolice/vo/firetodislocateinterpose.wav")
nut.voice.register("combine", "DISMOUNTING HARDPOINT", "Dismounting hardpoint.", "npc/metropolice/vo/dismountinghardpoint.wav")
nut.voice.register("combine", "DISP APB", "Disp updating APB likeness.", "npc/metropolice/vo/dispupdatingapb.wav")
nut.voice.register("combine", "DISTRIBUTION BLOCK", "Distribution block.", "npc/metropolice/vo/distributionblock.wav")
nut.voice.register("combine", "DOCUMENT", "Document.", "npc/metropolice/vo/document.wav")
nut.voice.register("combine", "DONT MOVE", "Don't move!", "npc/metropolice/vo/dontmove.wav")
nut.voice.register("combine", "ECHO", "Echo.", "npc/combine_soldier/vo/echo.wav")
nut.voice.register("combine", "ENGAGING", "Engaging!", "npc/combine_soldier/vo/engaging.wav")
nut.voice.register("combine", "ESTABLISH NEW CP", "Fall down, establish a new CP!", "npc/metropolice/vo/establishnewcp.wav")
nut.voice.register("combine", "EXPOSE TARGET", "Firing to expose target!", "npc/metropolice/vo/firingtoexposetarget.wav")
nut.voice.register("combine", "EXTERNAL", "External jurisdiction.", "npc/metropolice/vo/externaljurisdiction.wav")
nut.voice.register("combine", "FINAL VERDICT", "Final verdict administered.", "npc/metropolice/vo/finalverdictadministered.wav")
nut.voice.register("combine", "FINAL WARNING", "Final warning!", "npc/metropolice/vo/finalwarning.wav")
nut.voice.register("combine", "FIRST WARNING", "First warning, move away!", "npc/metropolice/vo/firstwarningmove.wav")
nut.voice.register("combine", "FIST", "Fist.", "npc/combine_soldier/vo/fist.wav")
nut.voice.register("combine", "FLASH", "Flash.", "npc/combine_soldier/vo/flash.wav")
nut.voice.register("combine", "FLATLINE", "Flatline.", "npc/combine_soldier/vo/flatline.wav")
nut.voice.register("combine", "FLUSH", "Flush.", "npc/combine_soldier/vo/flush.wav")
nut.voice.register("combine", "FREE NECROTICS", "I have free necrotics!", "npc/metropolice/vo/freenecrotics.wav")
nut.voice.register("combine", "GET DOWN", "Get down!", "npc/metropolice/vo/getdown.wav")
nut.voice.register("combine", "GET OUT", "Get out of here!", "npc/metropolice/vo/getoutofhere.wav")
nut.voice.register("combine", "GETTING 647E", "Still getting that 647-E from local surveillance.", "npc/metropolice/vo/stillgetting647e.wav")
nut.voice.register("combine", "GHOST", "Ghost.", "npc/combine_soldier/vo/ghost.wav")
nut.voice.register("combine", "GO AGAIN", "PT, go again.", "npc/metropolice/vo/ptgoagain.wav")
nut.voice.register("combine", "GO SHARP", "Go sharp!", "npc/combine_soldier/vo/gosharp.wav")
nut.voice.register("combine", "GOING IN", "Cover me, I'm going in!", "npc/metropolice/vo/covermegoingin.wav")
nut.voice.register("combine", "GOT A DB", "Uh, we got a DB here, cancel that 11-42.", "npc/metropolice/vo/wegotadbherecancel10-102.wav")
nut.voice.register("combine", "GOT HIM AGAIN", "Got him again, suspect is 10-20 at...", "npc/metropolice/vo/gothimagainsuspect10-20at.wav")
nut.voice.register("combine", "GOT ONE ACCOMPLICE", "I got one accomplice here!", "npc/metropolice/vo/gotoneaccompliceherea.wav")
nut.voice.register("combine", "GOT SUSPECT ONE", "I got suspect one here!", "npc/metropolice/vo/gotsuspect1here.wav")
nut.voice.register("combine", "GRENADE", "Grenade!", "npc/metropolice/vo/grenade.wav")
nut.voice.register("combine", "GRID", "Grid.", "npc/combine_soldier/vo/grid.wav")
nut.voice.register("combine", "HAHA", "Haha.", "npc/metropolice/vo/chuckle.wav")
nut.voice.register("combine", "HAMMER", "Hammer.", "npc/combine_soldier/vo/hammer.wav")
nut.voice.register("combine", "HARDPOINT PROSECUTE", "Is at hardpoint, ready to prosecute!", "npc/metropolice/vo/isathardpointreadytoprosecute.wav")
nut.voice.register("combine", "HARDPOINT SCANNING", "Hardpoint scanning.", "npc/metropolice/vo/hardpointscanning.wav")
nut.voice.register("combine", "HELIX", "Helix.", "npc/combine_soldier/vo/helix.wav")
nut.voice.register("combine", "HELP", "Help!", "npc/metropolice/vo/help.wav")
nut.voice.register("combine", "HERO", "Hero!", "npc/metropolice/vo/hero.wav")
nut.voice.register("combine", "HES 148", "He's gone 148!", "npc/metropolice/vo/hesgone148.wav")
nut.voice.register("combine", "HIGH PRIORITY", "High-priority region.", "npc/metropolice/vo/highpriorityregion.wav")
nut.voice.register("combine", "HOLD IT", "Hold it right there!", "npc/metropolice/vo/holditrightthere.wav")
nut.voice.register("combine", "HOLD POSITION", "Protection-team, hold this position.", "npc/metropolice/vo/holdthisposition.wav")
nut.voice.register("combine", "HOLD", "Hold it!", "npc/metropolice/vo/holdit.wav")
nut.voice.register("combine", "HUNTER", "Hunter.", "npc/combine_soldier/vo/hunter.wav")
nut.voice.register("combine", "HURRICANE", "Hurricane.", "npc/combine_soldier/vo/hurricane.wav")
nut.voice.register("combine", "I SAID MOVE", "I said move along.", "npc/metropolice/vo/Isaidmovealong.wav")
nut.voice.register("combine", "ICE", "Ice.", "npc/combine_soldier/vo/ice.wav")
nut.voice.register("combine", "IN POSITION", "In position.", "npc/metropolice/vo/inposition.wav")
nut.voice.register("combine", "INBOUND", "Inbound.", "npc/combine_soldier/vo/inbound.wav")
nut.voice.register("combine", "INFECTED", "Infected.", "npc/combine_soldier/vo/infected.wav")
nut.voice.register("combine", "INFECTION", "Infection!", "npc/metropolice/vo/infection.wav")
nut.voice.register("combine", "INFESTED", "Infested zone.", "npc/metropolice/vo/infestedzone.wav")
nut.voice.register("combine", "INJECT", "Inject!", "npc/metropolice/vo/inject.wav")
nut.voice.register("combine", "INOCULATE", "Inoculate.", "npc/metropolice/vo/innoculate.wav")
nut.voice.register("combine", "INTERCEDE", "Intercede!", "npc/metropolice/vo/intercede.wav")
nut.voice.register("combine", "INTERLOCK", "Interlock!", "npc/metropolice/vo/interlock.wav")
nut.voice.register("combine", "INVESTIGATE", "Investigate.", "npc/metropolice/vo/investigate.wav")
nut.voice.register("combine", "INVESTIGATING", "Investigating 10-103.", "npc/metropolice/vo/investigating10-103.wav")
nut.voice.register("combine", "ION", "Ion.", "npc/combine_soldier/vo/ion.wav")
nut.voice.register("combine", "IS 10-108", "Is 10-108!", "npc/metropolice/vo/is10-108.wav")
nut.voice.register("combine", "IS 10-8", "Unit is 10-8, standing by.", "npc/metropolice/vo/unitis10-8standingby.wav")
nut.voice.register("combine", "IS CLOSING", "Is closing on suspect!", "npc/metropolice/vo/isclosingonsuspect.wav")
nut.voice.register("combine", "IS DOWN", "Is down!", "npc/metropolice/vo/isdown.wav")
nut.voice.register("combine", "IS INBOUND", "Unit is inbound.", "npc/combine_soldier/vo/unitisinbound.wav")
nut.voice.register("combine", "IS MOVING IN", "Unit is moving in.", "npc/combine_soldier/vo/unitismovingin.wav")
nut.voice.register("combine", "IS MOVING", "Is moving in!", "npc/metropolice/vo/ismovingin.wav")
nut.voice.register("combine", "IS PASSIVE", "Is passive.", "npc/metropolice/vo/ispassive.wav")
nut.voice.register("combine", "IS READY TO GO", "Is ready to go!", "npc/metropolice/vo/isreadytogo.wav")
nut.voice.register("combine", "ISOLATE", "Isolate!", "npc/metropolice/vo/isolate.wav")
nut.voice.register("combine", "JET", "Jet.", "npc/combine_soldier/vo/jet.wav")
nut.voice.register("combine", "JUDGE", "Judge!", "npc/combine_soldier/vo/judge.wav")
nut.voice.register("combine", "JUDGE", "Judge.", "npc/combine_soldier/vo/judge.wav")
nut.voice.register("combine", "JUDGMENT", "Suspect, prepare to receive civil judgment!", "npc/metropolice/vo/prepareforjudgement.wav")
nut.voice.register("combine", "JURISDICTION", "Stabilization-jurisdiction.", "npc/metropolice/vo/stabilizationjurisdiction.wav")
nut.voice.register("combine", "JURY", "Jury!", "npc/metropolice/vo/jury.wav")
nut.voice.register("combine", "KEEP MOVING", "Keep moving!", "npc/metropolice/vo/keepmoving.wav")
nut.voice.register("combine", "KILO", "Kilo.", "npc/combine_soldier/vo/kilo.wav")
nut.voice.register("combine", "KING", "King!", "npc/metropolice/vo/king.wav")
nut.voice.register("combine", "LAST SEEN AT", "Hiding, last seen at range...", "npc/metropolice/vo/hidinglastseenatrange.wav")
nut.voice.register("combine", "LEADER", "Leader.", "npc/combine_soldier/vo/leader.wav")
nut.voice.register("combine", "LEVEL 3", "I have a level three civil-privacy violator here!", "npc/metropolice/vo/level3civilprivacyviolator.wav")
nut.voice.register("combine", "LINE", "Line!", "npc/metropolice/vo/line.wav")
nut.voice.register("combine", "LOCATION", "Location?", "npc/metropolice/vo/location.wav")
nut.voice.register("combine", "LOCK POSITION", "All units, lock your position!", "npc/metropolice/vo/lockyourposition.wav")
nut.voice.register("combine", "LOCK", "Lock!", "npc/metropolice/vo/lock.wav")
nut.voice.register("combine", "LOOK OUT", "Look out!", "npc/metropolice/vo/lookout.wav")
nut.voice.register("combine", "LOOSE PARASITICS", "Loose parasitics!", "npc/metropolice/vo/looseparasitics.wav")
nut.voice.register("combine", "LOST CONTACT", "Lost contact!", "npc/combine_soldier/vo/lostcontact.wav")
nut.voice.register("combine", "LOW ON", "Running low on verdicts, taking cover!", "npc/metropolice/vo/runninglowonverdicts.wav")
nut.voice.register("combine", "MACE", "Mace.", "npc/combine_soldier/vo/mace.wav")
nut.voice.register("combine", "MAINTAIN CP", "All units, maintain this CP!", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
nut.voice.register("combine", "MALCOMPLIANCE", "Issuing malcompliance citation.", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
nut.voice.register("combine", "MALCOMPLIANT 10-107", "Malcompliant 10-107 at my 10-20, preparing to prosecute.", "npc/metropolice/vo/malcompliant10107my1020.wav")
nut.voice.register("combine", "MALIGNANT", "Malignant!", "npc/metropolice/vo/malignant.wav")
nut.voice.register("combine", "MATCH ON APB", "I have a match on APB likeness.", "npc/metropolice/vo/matchonapblikeness.wav")
nut.voice.register("combine", "MINOR HITS", "Minor hits, continuing prosecution!", "npc/metropolice/vo/minorhitscontinuing.wav")
nut.voice.register("combine", "MOVE ALONG", "Move along!", "npc/metropolice/vo/movealong.wav")
nut.voice.register("combine", "MOVE BACK", "Move back, right now!", "npc/metropolice/vo/movebackrightnow.wav")
nut.voice.register("combine", "MOVE IN", "Move in!", "npc/combine_soldier/vo/movein.wav")
nut.voice.register("combine", "MOVE IT", "Move it!", "npc/metropolice/vo/moveit.wav")
nut.voice.register("combine", "MOVE", "Move!", "npc/metropolice/vo/move.wav")
nut.voice.register("combine", "MOVING TO COVER", "Moving to cover!", "npc/metropolice/vo/movingtocover.wav")
nut.voice.register("combine", "MOVING TO HARDPOINT", "Moving to hardpoint!", "npc/metropolice/vo/movingtohardpoint.wav")
nut.voice.register("combine", "NECROTICS", "Necrotics!", "npc/metropolice/vo/necrotics.wav")
nut.voice.register("combine", "NEED ANY HELP", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
nut.voice.register("combine", "NEEDS ASSISTANCE", "Officer needs assistance, I am 11-99!", "npc/metropolice/vo/officerneedsassistance.wav")
nut.voice.register("combine", "NEEDS HELP", "Officer needs help!", "npc/metropolice/vo/officerneedshelp.wav")
nut.voice.register("combine", "NO 647", "Clear, no 647, no 10-107.", "npc/metropolice/vo/clearno647no10-107.wav")
nut.voice.register("combine", "NO CONTACT", "No contact!", "npc/metropolice/vo/nocontact.wav")
nut.voice.register("combine", "NO I'M GOOD", "No, I'm good.", "vo/trainyard/ba_noimgood.wav")
nut.voice.register("combine", "NO VISUAL ON", "No visual on UPI at this time.", "npc/metropolice/vo/novisualonupi.wav")
nut.voice.register("combine", "NOMAD", "Nomad.", "npc/combine_soldier/vo/nomad.wav")
nut.voice.register("combine", "NONCITIZEN", "Noncitizen.", "npc/metropolice/vo/noncitizen.wav")
nut.voice.register("combine", "NONPATROL", "Non-patrol region.", "npc/metropolice/vo/nonpatrolregion.wav")
nut.voice.register("combine", "NONTAGGED VIROMES", "Non-tagged viromes here!", "npc/metropolice/vo/non-taggedviromeshere.wav")
nut.voice.register("combine", "NOVA", "Nova.", "npc/combine_soldier/vo/nova.wav")
nut.voice.register("combine", "NOW GET OUT", "Now, get out of here!", "npc/metropolice/vo/nowgetoutofhere.wav")
nut.voice.register("combine", "NOW", "Now.", "vo/trainyard/ba_thatbeer01.wav")
nut.voice.register("combine", "OUTBREAK", "Outbreak!", "npc/combine_soldier/vo/outbreak.wav")
nut.voice.register("combine", "OUTBREAK", "Outbreak!", "npc/metropolice/vo/outbreak.wav")
nut.voice.register("combine", "OVERWATCH", "Overwatch.", "npc/combine_soldier/vo/overwatch.wav")
nut.voice.register("combine", "PACIFYING", "Pacifying!", "npc/metropolice/vo/pacifying.wav")
nut.voice.register("combine", "PAIN1", "Ugh!", "npc/metropolice/pain1.wav")
nut.voice.register("combine", "PAIN2", "Uagh!", "npc/metropolice/pain2.wav")
nut.voice.register("combine", "PAIN3", "Augh!", "npc/metropolice/pain3.wav")
nut.voice.register("combine", "PAIN4", "Agh!", "npc/metropolice/pain4.wav")
nut.voice.register("combine", "PATROL", "Patrol!", "npc/metropolice/vo/patrol.wav")
nut.voice.register("combine", "PAYBACK", "Payback.", "npc/combine_soldier/vo/payback.wav")
nut.voice.register("combine", "PHANTOM", "Phantom.", "npc/combine_soldier/vo/phantom.wav")
nut.voice.register("combine", "PICKUP 647E", "Anyone else pick up a, uh... 647-E reading?", "npc/metropolice/vo/anyonepickup647e.wav")
nut.voice.register("combine", "POSITION AT HARDPOINT", "In position at hardpoint.", "npc/metropolice/vo/inpositionathardpoint.wav")
nut.voice.register("combine", "POSITION TO CONTAIN", "Position to contain.", "npc/metropolice/vo/positiontocontain.wav")
nut.voice.register("combine", "POSSIBLE 404", "Possible 404 here!", "npc/metropolice/vo/possible404here.wav")
nut.voice.register("combine", "POSSIBLE 647E", "Possible 647-E here, request AirWatch tag.", "npc/metropolice/vo/possible647erequestairwatch.wav")
nut.voice.register("combine", "POSSIBLE ACCOMPLICE", "Report sightings of possible accomplice.", "npc/metropolice/vo/reportsightingsaccomplices.wav")
nut.voice.register("combine", "POSSIBLE LEVEL 3", "Possible level three civil-privacy violator here!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav")
nut.voice.register("combine", "PREPARING TO JUDGE", "Preparing to judge a 10-107, be advised.", "npc/metropolice/vo/preparingtojudge10-107.wav")
nut.voice.register("combine", "PRESERVE", "Preserve!", "npc/metropolice/vo/preserve.wav")
nut.voice.register("combine", "PRESSURE", "Pressure!", "npc/metropolice/vo/pressure.wav")
nut.voice.register("combine", "PRIORITY 1", "Confirm, priority-one sighted.", "npc/metropolice/vo/confirmpriority1sighted.wav")
nut.voice.register("combine", "PRIORITY 2", "I have a priority-two anti-citizen here!", "npc/metropolice/vo/priority2anticitizenhere.wav")
nut.voice.register("combine", "PRODUCTION BLOCK", "Production-block.", "npc/metropolice/vo/productionblock.wav")
nut.voice.register("combine", "PROSECUTE MALCOMPLIANT", "Ready to prosecute malcompliant citizen, final warning issued!", "npc/metropolice/vo/readytoprosecutefinalwarning.wav")
nut.voice.register("combine", "PROSECUTE", "Prosecute!", "npc/metropolice/vo/prosecute.wav")
nut.voice.register("combine", "PROSECUTING", "Prosecuting.", "npc/combine_soldier/vo/procecuting.")
nut.voice.register("combine", "PROTECTION COMPLETE", "Protection complete.", "npc/metropolice/vo/protectioncomplete.wav")
nut.voice.register("combine", "QUICK", "Quick!", "npc/metropolice/vo/quick.wav")
nut.voice.register("combine", "QUICKSAND", "Quicksand.", "npc/combine_soldier/vo/quicksand.wav")
nut.voice.register("combine", "RANGE", "Range.", "npc/combine_soldier/vo/range.wav")
nut.voice.register("combine", "RANGER", "Ranger.", "npc/combine_soldier/vo/ranger.wav")
nut.voice.register("combine", "RAZOR", "Razor.", "npc/combine_soldier/vo/razor.wav")
nut.voice.register("combine", "READY AMPUTATE", "Ready to amputate!", "npc/metropolice/vo/readytoamputate.wav")
nut.voice.register("combine", "READY CHARGES", "Ready charges!", "npc/combine_soldier/vo/readycharges.wav")
nut.voice.register("combine", "READY JUDGE", "Ready to judge.", "npc/metropolice/vo/readytojudge.wav")
nut.voice.register("combine", "READY PROSECUTE", "Ready to prosecute!", "npc/metropolice/vo/readytoprosecute.wav")
nut.voice.register("combine", "READY WEAPONS", "Ready weapons!", "npc/combine_soldier/vo/readyweapons.wav")
nut.voice.register("combine", "REAPER", "Reaper.", "npc/combine_soldier/vo/reaper.wav")
nut.voice.register("combine", "REINFORCEMENT TEAMS", "Reinforcement-teams, code three!", "npc/metropolice/vo/reinforcementteamscode3.wav")
nut.voice.register("combine", "REPORT CLEAR", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav")
nut.voice.register("combine", "REPORT IN", "CP requests all units, uhh... Location report-in.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
nut.voice.register("combine", "REPORT LOCATION", "All units, report location suspect!", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
nut.voice.register("combine", "REPORT STATUS", "Local CP-teams, report status.", "npc/metropolice/vo/localcptreportstatus.wav")
nut.voice.register("combine", "REPURPOSED", "Repurposed area.", "npc/metropolice/vo/repurposedarea.wav")
nut.voice.register("combine", "RESIDENTIAL BLOCK", "Residential block.", "npc/metropolice/vo/residentialblock.wav")
nut.voice.register("combine", "RESPOND CODE 3", "All units at location, responding code three!", "npc/metropolice/vo/allunitsrespondcode3.wav")
nut.voice.register("combine", "RESPONDING", "Responding.", "npc/metropolice/vo/responding2.wav")
nut.voice.register("combine", "RESTRICT", "Restrict!", "npc/metropolice/vo/restrict.wav")
nut.voice.register("combine", "RESTRICTED", "Restricted block.", "npc/metropolice/vo/restrictedblock.wav")
nut.voice.register("combine", "RESTRICTION ZONE", "Terminal restriction-zone!", "npc/metropolice/vo/terminalrestrictionzone.wav")
nut.voice.register("combine", "RIPCORD", "Ripcord!", "npc/combine_soldier/vo/ripcord.wav")
nut.voice.register("combine", "RODGER THAT", "Rodger that!", "npc/metropolice/vo/rodgerthat.wav")
nut.voice.register("combine", "ROLLER", "Roller!", "npc/metropolice/vo/roller.wav")
nut.voice.register("combine", "RUNNING", "He's running!", "npc/metropolice/vo/hesrunning.wav")
nut.voice.register("combine", "SACRIFICE CODE", "All units, sacrifice code one and maintain this CP!", "npc/metropolice/vo/sacrificecode1maintaincp.wav")
nut.voice.register("combine", "SAVAGE", "Savage.", "npc/combine_soldier/vo/savage.wav")
nut.voice.register("combine", "SCAR", "Scar.", "npc/combine_soldier/vo/scar.wav")
nut.voice.register("combine", "SEARCH", "Search!", "npc/metropolice/vo/search.wav")
nut.voice.register("combine", "SEARCHING FOR SUSPECT", "Searching for suspect.", "npc/metropolice/vo/searchingforsuspect.wav")
nut.voice.register("combine", "SECOND WARNING", "This is your second warning!", "npc/metropolice/vo/thisisyoursecondwarning.wav")
nut.voice.register("combine", "SECTOR NOT STERILE", "Confirmed- sector not sterile.", "npc/combine_soldier/vo/confirmsectornotsterile.wav")
nut.voice.register("combine", "SECTOR SECURE", "Sector is now secure.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
nut.voice.register("combine", "SECURE ADVANCE", "Assault-point secured, advance!", "npc/metropolice/vo/assaultpointsecureadvance.wav")
nut.voice.register("combine", "SECURE", "Secure.", "npc/combine_soldier/vo/secure.wav")
nut.voice.register("combine", "SENTENCE", "Sentence delivered.", "npc/metropolice/vo/sentencedelivered.wav")
nut.voice.register("combine", "SERVE", "Serve.", "npc/metropolice/vo/serve.wav")
nut.voice.register("combine", "SHADOW", "Shadow.", "npc/combine_soldier/vo/shadow.wav")
nut.voice.register("combine", "SHARPZONE", "Sharpzone.", "npc/combine_soldier/vo/sharpzone.wav")
nut.voice.register("combine", "SHIT", "Shit!", "npc/metropolice/vo/shit.wav")
nut.voice.register("combine", "SHOTS FIRED", "Shots fired, hostile malignants here!", "npc/metropolice/vo/shotsfiredhostilemalignants.wav")
nut.voice.register("combine", "SLAM", "Slam.", "npc/combine_soldier/vo/slam.wav")
nut.voice.register("combine", "SLASH", "Slash.", "npc/combine_soldier/vo/slash.wav")
nut.voice.register("combine", "SOCIOCIDE", "Sociocide.", "npc/metropolice/vo/sociocide.wav")
nut.voice.register("combine", "SOCIOSTABLE", "We are socio-stable at this location.", "npc/metropolice/vo/wearesociostablethislocation.wav")
nut.voice.register("combine", "SPEAR", "Spear.", "npc/combine_soldier/vo/spear.wav")
nut.voice.register("combine", "STAB", "Stab.", "npc/combine_soldier/vo/stab.wav")
nut.voice.register("combine", "STANDING BY", "Standing by.", "npc/combine_soldier/vo/standingby].wav")
nut.voice.register("combine", "STAR", "Star.", "npc/combine_soldier/vo/star.wav")
nut.voice.register("combine", "STATIONBLOCK", "Stationblock.", "npc/metropolice/vo/stationblock.wav")
nut.voice.register("combine", "STAY ALERT", "Stay alert.", "npc/combine_soldier/vo/stayalert.wav")
nut.voice.register("combine", "STERILIZE", "Sterilize!", "npc/metropolice/vo/sterilize.wav")
nut.voice.register("combine", "STINGER", "Stinger.", "npc/combine_soldier/vo/stringer.wav")
nut.voice.register("combine", "STORM", "Storm.", "npc/combine_soldier/vo/storm.wav")
nut.voice.register("combine", "STRIKE", "Striker.", "npc/combine_soldier/vo/striker.wav")
nut.voice.register("combine", "SUBJECT 505", "Subject is 505!", "npc/metropolice/vo/subjectis505.wav")
nut.voice.register("combine", "SUBJECT HIGH SPEED", "All units, be advised, subject is now high-speed!", "npc/metropolice/vo/subjectisnowhighspeed.wav")
nut.voice.register("combine", "SUBJECT", "Subject!", "npc/metropolice/vo/subject.wav")
nut.voice.register("combine", "SUNDOWN", "Sundown.", "npc/combine_soldier/vo/sundown.wav")
nut.voice.register("combine", "SUSPECT INCURSION", "Disp reports suspect-incursion at location.", "npc/metropolice/vo/dispreportssuspectincursion.wav")
nut.voice.register("combine", "SUSPECT MOVED TO", "Suspect has moved now to...", "npc/metropolice/vo/supsecthasnowmovedto.wav")
nut.voice.register("combine", "SUSPECT RESTRICTED CANALS", "Suspect is using restricted canals at...", "npc/metropolice/vo/suspectusingrestrictedcanals.wav")
nut.voice.register("combine", "SUSPEND", "Suspend!", "npc/metropolice/vo/suspend.wav")
nut.voice.register("combine", "SWEEPER", "Sweeper.", "npc/combine_soldier/vo/sweeper.wav")
nut.voice.register("combine", "SWEEPING IN", "Sweeping in!", "npc/combine_soldier/vo/sweepingin.wav")
nut.voice.register("combine", "SWEEPING SUSPECT", "Sweeping for suspect!", "npc/metropolice/vo/sweepingforsuspect.wav")
nut.voice.register("combine", "SWIFT", "Swift.", "npc/combine_soldier/vo/swift.wav")
nut.voice.register("combine", "SWORD", "Sword.", "npc/combine_soldier/vo/sword.wav")
nut.voice.register("combine", "TAG 10-91D", "Tag 10-91d!", "npc/metropolice/vo/tag10-91d.wav")
nut.voice.register("combine", "TAG BUG", "Tag one bug!", "npc/metropolice/vo/tagonebug.wav")
nut.voice.register("combine", "TAG NECROTIC", "Tag one necrotic!", "npc/metropolice/vo/tagonenecrotic.wav")
nut.voice.register("combine", "TAG PARASITIC", "Tag one parasitic!", "npc/metropolice/vo/tagoneparasitic.wav")
nut.voice.register("combine", "TAKE A LOOK", "Going to take a look!", "npc/metropolice/vo/goingtotakealook.wav")
nut.voice.register("combine", "TAKE COVER", "Take cover!", "npc/metropolice/vo/takecover.wav")
nut.voice.register("combine", "TAP", "Tap!", "npc/metropolice/vo/tap.wav")
nut.voice.register("combine", "TARGET", "Target.", "npc/combine_soldier/vo/target.wav")
nut.voice.register("combine", "TEAM ADVANCE", "Team in position, advance!.", "npc/metropolice/vo/teaminpositionadvance.wav")
nut.voice.register("combine", "TEAM HOLDING", "Stabilization team holding in position.", "npc/combine_soldier/vo/stabilizationteamholding.wav")
nut.voice.register("combine", "THERE HE GOES", "There he goes! He's at...", "npc/metropolice/vo/therehegoeshesat.wav")
nut.voice.register("combine", "THERE HE IS", "There he is!", "npc/metropolice/vo/thereheis.wav")
nut.voice.register("combine", "TRACKER", "Tracker.", "npc/combine_soldier/vo/tracker.wav")
nut.voice.register("combine", "TRANSITBLOCK", "Transit-block.", "npc/metropolice/vo/transitblock.wav")
nut.voice.register("combine", "TROUBLE", "Lookin' for trouble?", "npc/metropolice/vo/lookingfortrouble.wav")
nut.voice.register("combine", "UNDER FIRE", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav")
nut.voice.register("combine", "UNIFORM", "Uniform.", "npc/combine_soldier/vo/uniform.wav")
nut.voice.register("combine", "UNION", "Union!", "npc/metropolice/vo/union.wav")
nut.voice.register("combine", "UNKNOWN", "Suspect location unknown.", "npc/metropolice/vo/suspectlocationunknown.wav")
nut.voice.register("combine", "UP THERE", "He's up there!", "npc/metropolice/vo/hesupthere.wav")
nut.voice.register("combine", "UPI", "UPI.", "npc/metropolice/vo/upi.wav")
nut.voice.register("combine", "UTL SUSPECT", "UTL that suspect.", "npc/metropolice/vo/utlthatsuspect.wav")
nut.voice.register("combine", "UTL", "UTL suspect.", "npc/metropolice/vo/utlsuspect.wav")
nut.voice.register("combine", "VACATE", "Vacate, citizen!", "npc/metropolice/vo/vacatecitizen.wav")
nut.voice.register("combine", "VAMP", "Vamp.", "npc/combine_soldier/vo/vamp.wav")
nut.voice.register("combine", "VERDICT", "You want a malcompliance verdict?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav")
nut.voice.register("combine", "VICE", "Vice!", "npc/metropolice/vo/vice.wav")
nut.voice.register("combine", "VICTOR", "Victor!", "npc/metropolice/vo/victor.wav")
nut.voice.register("combine", "VISCON", "Viscon.", "npc/combine_soldier/vo/viscon.wav")
nut.voice.register("combine", "VISUAL EXOGEN", "Visual on exogen.", "npc/combine_soldier/vo/visualonexogen.wav")
nut.voice.register("combine", "WARNING GIVEN", "Second warning given!", "npc/metropolice/vo/secondwarning.wav")
nut.voice.register("combine", "WASTERIVER", "Wasteriver.", "npc/metropolice/vo/wasteriver.wav")
nut.voice.register("combine", "WATCH IT", "Watch it!", "npc/metropolice/vo/watchit.wav")
nut.voice.register("combine", "WINDER", "Winder.", "npc/combine_soldier/vo/winder.wav")
nut.voice.register("combine", "WORKFORCE", "Workforce intake.", "npc/metropolice/vo/workforceintake.wav")
nut.voice.register("combine", "WRAP IT UP", "That's it, wrap it up.", "npc/combine_soldier/vo/thatsitwrapitup.wav")
nut.voice.register("combine", "XRAY", "XRay!", "npc/metropolice/vo/xray.wav")
nut.voice.register("combine", "YEAH", "Yeah.", "npc/metropolice/mc1ans_yeah.wav")
nut.voice.register("combine", "YELLOW", "Yellow!", "npc/metropolice/vo/yellow.wav")
nut.voice.register("combine", "YEP", "Yep.", "npc/metropolice/mc1ans_yep.wav")
nut.voice.register("combine", "YOU CAN GO", "Alright, you can go.", "npc/metropolice/vo/allrightyoucango.wav")
nut.voice.register("combine", "ZONE", "Zone!", "npc/metropolice/vo/zone.wav")

-- Dispatch voices.
nut.voice.register("dispatch", "ACTIVITY LEVEL 1", "You are charged with anti-civil activity level: ONE. Protection-unit prosecution code: DUTY, SWORD, OPERATE.", "npc/overwatch/cityvoice/f_anticivil1_5_spkr.wav")
nut.voice.register("dispatch", "ANTI-CITIZEN", "Attention, ground-units: Anti-citizen reported in this community. Code: LOCK, CAUTERIZE, STABILIZE.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav")
nut.voice.register("dispatch", "ANTI-CIVIL EVIDENCE", "Protection-team, alert: Evidence of anti-civil activity in this community. Code: ASSEMBLE, CLAMP, CONTAIN.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav")
nut.voice.register("dispatch", "ARE CHARGED WITH", "Individual, you are charged with capital malcompliance. Anti-citizen status, APPROVED.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav")
nut.voice.register("dispatch", "ASSUME POSITIONS", "Attention, please: All citizens in local residential block, assume your inspection-positions.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav")
nut.voice.register("dispatch", "AUTONOMOUS JUDGMENT", "Attention, all ground-protection teams, autonomous judgment is now in effect. Sentencing is now discretionary. Code, AMPUTATE, ZERO, CONFIRM.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav")
nut.voice.register("dispatch", "CITIZEN RELOCATION", "Citizen notice: Failure to co-operate will result in permanent off-world relocation.", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav")
nut.voice.register("dispatch", "CONSPIRACY", "Citizen reminder: Inaction is conspiracy. Report counter-behavior to a Civil-Protection team immediately.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav")
nut.voice.register("dispatch", "CONVICTED", "Individual, you are convicted of multi-anti-civil violations. Implict citizenship revoked. Status, MALIGNANT.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav")
nut.voice.register("dispatch", "DEDUCTED", "Attention, occupants: Your block is now charged with permissive inactive coersion. Five ration-units deducted.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav")
nut.voice.register("dispatch", "EVASION BEHAVIOR", "Attention, please, evasion behaviour consistent with malcompliant defendant. Ground protection-team, alert, code: ISOLATE, EXPOSE, ADMINISTER.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav")
nut.voice.register("dispatch", "INDIVIDUAL CHARGED WITH", "Individual, you are charged with socio-endangerment level: ONE. Protection-unit prosecution code, DUTY, SWORD, MIDNIGHT.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav")
nut.voice.register("dispatch", "INSPECTION", "Citizen notice, priority identification-check in-progress. Please assemble in your designated inspection positions.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav")
nut.voice.register("dispatch", "JUDGMENT WAIVER", "Attention, all ground-protection teams, judgment waiver now in effect. Capital prosecution is discretionary.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav")
nut.voice.register("dispatch", "MISCOUNT DETECTED", "Attention, residents: Miscount detected in your block. Co-operation with your Civil Protection team permits full ration reward.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav")
nut.voice.register("dispatch", "MISSION FAILURE", "Attention, ground-units: Mission-failure will result in permanent off-world assignment. Code-reminder: SACRIFICE, COAGULATE, CLAMP.", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav")
nut.voice.register("dispatch", "OVERWATCH ACKNOWLEDGES", "Overwatch acknowledges critical exogen-breach. AirWatch augmentation-force dispatched and inbound. Hold for re-enforcement.", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav")
nut.voice.register("dispatch", "POTENTIAL INFECTION", "Attention, residents: This blocks contains potential civil infection. INFORM, CO-OPERATE, ASSEMBLE.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav")
nut.voice.register("dispatch", "RECEIVE YOUR VERDICT", "Individual, you are now charged with socio-endangerment level: FIVE. Cease evasion immediately, recieve your verdict.", "npc/overwatch/cityvoice/f_ceaseevasionlevelfive_spkr.wav")
nut.voice.register("dispatch", "STATUS EVASION", "Attention, protection-team, status evasion in progress in this community. RESPOND, ISOLATE, INQUIRE.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav")
nut.voice.register("dispatch", "UNIDENTIFIED", "Attention, please: Unidentified person of interest, confirm your civil status with local protection-team immediately.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav")
nut.voice.register("dispatch", "UNREST PROCEDURE", "Attention, community: Unrest procedure code is now in effect. INNOCULATE, SHIELD, PACIFY. Code: PRESSURE, SWORD, STERILIZE.", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav")
nut.voice.register("dispatch", "UNREST STRUCTURE", "Alert, community ground-protection units, local unrest structure detected. ASSEMBLE, ADMINISTER, PACIFY.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav")
